<a href="https://colab.research.google.com/github/HowardHNguyen/Data_Science_for_Marketing_Solutions/blob/main/ADE_Generating_Summary_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import relevant libraries

In [1]:
import numpy as np
import pandas as pd

#### Load data into dataframe

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
covid_data = pd.read_csv("/content/drive/MyDrive/_Python/Exploratory-Data-Analysis-with-Python/Ch1/Data/covid-data.csv")
#

#### Inspect the dataframe

In [4]:
covid_data.head(5)

iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  24/02/2020            5          5   
1      AFG      Asia  Afghanistan  25/02/2020            5          0   
2      AFG      Asia  Afghanistan  26/02/2020            5          0   
3      AFG      Asia  Afghanistan  27/02/2020            5          0   
4      AFG      Asia  Afghanistan  28/02/2020            5          0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   female_smokers  male_smokers  handwashing_facilities  \
0             NaN           NaN                  37.746   
1             NaN           NaN                  37.746   
2             NaN           NaN                  37.746   
3             NaN           NaN                  37.746   
4             NaN           NaN                  37.746   

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.5            64.83                    0.511   
1                         0.5            64.83                    0.511   
2                         0.5            64.83                    0.511   
3                         0.5            64.83                    0.511   
4                         0.5            64.83                    0.511   

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN   
1                                   NaN                          NaN   
2                                   NaN                          NaN   
3                                   NaN                          NaN   
4                                   NaN                          NaN   

   excess_mortality  excess_mortality_cumulative_per_million  
0               NaN                                      NaN  
1               NaN                                      NaN  
2               NaN                                      NaN  
3               NaN                                      NaN  
4               NaN                                      NaN  

[5 rows x 67 columns]

In [5]:
covid_data.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       't

In [6]:
covid_data.shape

(5818, 67)

In [7]:
covid_data = covid_data[['iso_code','continent','location','date','total_cases','new_cases']]

In [8]:
covid_data.head(5)

iso_code continent     location        date  total_cases  new_cases
0      AFG      Asia  Afghanistan  24/02/2020            5          5
1      AFG      Asia  Afghanistan  25/02/2020            5          0
2      AFG      Asia  Afghanistan  26/02/2020            5          0
3      AFG      Asia  Afghanistan  27/02/2020            5          0
4      AFG      Asia  Afghanistan  28/02/2020            5          0

In [9]:
covid_data.dtypes

iso_code       object
continent      object
location       object
date           object
total_cases     int64
new_cases       int64
dtype: object

In [10]:
covid_data.shape

(5818, 6)

## Analyse the mean
The mean is considered the average of a dataset. It is typically used on tabular data, and it provides us with a sense of where the center of the dataset lies. To calculate the mean, we need to sum up all the data points and divide the sum by the number of data points in our dataset. The mean is very sensitive to outliers. Outliers are unusually high or unusually low data points that are far from other data points in our dataset. They typically lead to anomalies in the output of our analysis. Since unusually high or low numbers will affect the sum of data points without affecting the number of data points, these outliers can heavily influence the mean of a dataset. However, the mean is still very useful for inspecting a dataset to get quick insights into the average of the dataset.

In [11]:
data_mean = np.mean(covid_data["new_cases"])
data_mean

8814.365761430045

In [12]:
data_mean = covid_data["new_cases"].mean()
data_mean

8814.365761430045

## Checking the median of a dataset

The median is the middle value within a sorted dataset (ascending or descending order). Half of the data points in the dataset are less than the median, and the other half of the data points are greater than the median. The median is like the mean because it is also typically used on tabular data, and the “middle value” provides us with a sense of where the center of a dataset lies.

However, unlike the mean, the median is not sensitive to outliers. Outliers are unusually high or unusually low data points in our dataset, which can result in misleading analysis. The median isn’t heavily influenced by outliers because it doesn’t require the sum of all datapoints as the mean does; it only selects the middle value from a sorted dataset. To calculate the median, we sort the dataset and select the middle value if the number of datapoints is odd. If it is even, we select the two middle values and find the average to get the median. The median is a very useful statistic to get quick insights into the middle of a dataset. Depending on the distribution of the data, sometimes the mean and median can be the same number, while in other cases, they are different numbers. Checking for both statistics is usually a good idea.

In [13]:
data_median = np.median(covid_data["new_cases"])
data_median

261.0

## Identify the mode of the continent column
The mode is the value that occurs most frequently in the dataset, or simply put, the most common value in a dataset. Unlike the mean and median, which must be applied to numeric values, the mode can be applied to both numeric and non-numeric values since the focus is on the frequency at which a value occurs. The mode provides quick insights into the most common value. It is a very useful statistic, especially when used alongside the mean and median of a dataset.

In [15]:
from scipy import stats

In [14]:
data_mode = covid_data["continent"].mode()
data_mode

0    Europe
Name: continent, dtype: object

In [16]:
data_mode = stats.mode(covid_data["continent"])
data_mode

TypeError: Argument `a` is not recognized as numeric. Support for input that cannot be coerced to a numeric array was deprecated in SciPy 1.9.0 and removed in SciPy 1.11.0. Please consider `np.unique`.

In [18]:
#data_mode = stats.mode(covid_data["continent"].astype(str))
covid_data['continent_codes'] = pd.factorize(covid_data['continent'])[0]
data_mode = stats.mode(covid_data['continent_codes'])
data_mode

ModeResult(mode=2, count=1963)

## Check the variance of a dataset

The new_cases column using the var method in numpy

Just like we may want to know where the center of a dataset lies, we may also want to know how widely spread the dataset is, for example, how far apart the numbers in the dataset are from each other. The variance helps us achieve this. Unlike the mean, median, and mode, which give us a sense of where the center of the dataset lies, the variance gives us a sense of the spread of a dataset or the variability.

In [19]:
data_variance = np.var(covid_data["new_cases"])
data_variance

451321915.92810047

## Identify the Standard Deviation
The standard deviation is derived from the variance and is simply the square root of the variance. The standard deviation is typically more intuitive because it is expressed in the same units as the dataset, for example, kilometers (km). On the other hand, the variance is typically expressed in units larger than the dataset and can be less intuitive, for example, kilometers squared (km2).

In [20]:
data_sd = np.std(covid_data["new_cases"])
data_sd

21244.33844411495

## Range of the a dataset
The range also helps us understand the spread of a dataset or how far apart the dataset’s numbers are from each other. It is the difference between the minimum and maximum values within a dataset. It is a very useful statistic, especially when used alongside the variance and standard deviation of a dataset.

In [22]:
data_max = np.max(covid_data["new_cases"])
data_min = np.min(covid_data["new_cases"])
data_range = data_max - data_min
print(data_max)
print(data_min)
print(data_range)

287149
0
287149


## Percentiles of dataset
The percentile is an interesting statistic because it can be used to measure the spread of a dataset and, at the same time, identify the center of a dataset. The percentile divides the dataset into 100 equal portions, allowing us to determine the values in a dataset above or below a certain limit. Typically, 99 percentiles will split your dataset into 100 equal portions. The value of the 50th percentile is the same value as the median.

In [23]:
data_percentiles = np.percentile(covid_data["new_cases"], [25,50,75])
data_percentiles

array([  24.,  261., 3666.])

In [24]:
data_percentiles = np.percentile(covid_data["new_cases"], [0,100])
data_percentiles

array([     0., 287149.])

In [26]:
data_percentiles = np.percentile(covid_data["new_cases"], 60)
data_percentiles

591.3999999999996

## Quartiles of dataset
The quartile is like the percentile because it can be used to measure the spread and identify the center of a dataset. Percentiles and quartiles are called quantiles. While the percentile divides the dataset into 100 equal portions, the quartile divides the dataset into 4 equal portions. Typically, three quartiles will split your dataset into four equal portions.

In [27]:
data_quartiles = np.quantile(covid_data["new_cases"], [0.25,0.5,0.75])
data_quartiles

array([  24.,  261., 3666.])

In [28]:
data_quartiles = np.quantile(covid_data["new_cases"], [0,1])
data_quartiles

array([     0, 287149])

In [30]:
data_quartiles = np.quantile(covid_data["new_cases"], 0.75)
data_quartiles

3666.0

## Interquartile range (IQR) of dataset
The IQR also measures the spread or variability of a dataset. It is simply the distance between the first and third quartiles. The IQR is a very useful statistic, especially when we need to identify where the middle 50% of values in a dataset lie. Unlike the range, which can be skewed by very high or low numbers (outliers), the IQR isn’t affected by outliers since it focuses on the middle 50. It is also useful when we need to compute for outliers in a dataset.

In [31]:
data_iqr = stats.iqr(covid_data["new_cases"])
data_iqr

3642.0